-- MySQL Script generated by MySQL Workbench
-- Tue Oct 19 23:02:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema PadelStore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PadelStore` ;

-- -----------------------------------------------------
-- Schema PadelStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PadelStore` ;
USE `PadelStore` ;

-- -----------------------------------------------------
-- Table `PadelStore`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PadelStore`.`user` ;

CREATE TABLE IF NOT EXISTS `PadelStore`.`user` (
  `Id` VARCHAR(15) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `firtname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `mail` VARCHAR(50) NULL DEFAULT NULL,
  `phone` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PadelStore`.`user_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PadelStore`.`user_address` ;

CREATE TABLE IF NOT EXISTS `PadelStore`.`user_address` (
  `IdAddress` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(15) NOT NULL,
  `address` VARCHAR(150) NULL DEFAULT NULL,
  `county` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `postal_code` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IdAddress`),
  INDEX `user_user_address_idx` (`user_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PadelStore`.`user_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PadelStore`.`user_cards` ;

CREATE TABLE IF NOT EXISTS `PadelStore`.`user_cards` (
  `IdCards` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(15) NOT NULL,
  `card_number` INT NULL DEFAULT NULL,
  `ping` INT NULL DEFAULT NULL,
  `data_exp` VARCHAR(6) NULL DEFAULT NULL,
  PRIMARY KEY (`IdCards`),
  INDEX `user_user_cards_idx` (`user_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PadelStore`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PadelStore`.`product` ;

CREATE TABLE IF NOT EXISTS `PadelStore`.`product` (
  `Id` INT NOT NULL,
  `name` VARCHAR(60) NULL DEFAULT NULL,
  `description` TEXT(150) NULL DEFAULT NULL,
  `category_id` INT NOT NULL,
  `price` DECIMAL(15) NULL DEFAULT NULL,
  `discount_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP(6) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`, `category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PadelStore`.`shopping_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PadelStore`.`shopping_cart` ;

CREATE TABLE IF NOT EXISTS `PadelStore`.`shopping_cart` (
  `Id` INT NULL DEFAULT NULL,
  `session_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`session_id`, `product_id`),
  INDEX `product_shopping_cart_idx` (`product_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PadelStore`.`payment_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PadelStore`.`payment_details` ;

CREATE TABLE IF NOT EXISTS `PadelStore`.`payment_details` (
  `Id` INT NOT NULL,
  `order_id` INT NULL DEFAULT NULL,
  `total_amount` DECIMAL(50) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PadelStore`.`order_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PadelStore`.`order_detail` ;

CREATE TABLE IF NOT EXISTS `PadelStore`.`order_detail` (
  `Id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `total` DECIMAL(50) NULL DEFAULT NULL,
  `payment_id` INT NOT NULL,
  `created_at` TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`, `user_id`, `payment_id`),
  INDEX `user_order_detail_idx` (`user_id` ASC) ,
  INDEX `product_order_detail_idx` (`payment_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PadelStore`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PadelStore`.`product_category` ;

CREATE TABLE IF NOT EXISTS `PadelStore`.`product_category` (
  `Id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` TEXT(150) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
